# Generated by Django 5.1.6 on 2025-02-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=50, verbose_name='음식점 이름')),
                ('address', models.CharField(max_length=200, verbose_name='음식점 주소')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처 정보')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='영업 시작 시간 ')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='영업 종료 시간 ')),
                ('last_order', models.TimeField(blank=True, null=True, verbose_name='마지막 주문 시간 ')),
                ('regular_holiday', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
