# Generated by Django 5.0.7 on 2024-07-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_completed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='todo/no_image/NO-IMAGE.gif', null=True, upload_to='todo/thumbnails'),
        ),
    ]
